# Generated by Django 3.2.13 on 2022-05-15 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0002_auto_20220515_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='spent_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 19, 53, 19, 834528), verbose_name='Time spent'),
        ),
    ]
