# Generated by Django 3.2.13 on 2022-05-15 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0003_alter_spendings_spent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('spent_at', models.DateTimeField(default=datetime.datetime(2022, 5, 15, 22, 21, 12, 180410), verbose_name='Time spent')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('HUF', 'HUF')], default='HUF', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Spendings',
        ),
    ]
