# Generated by Django 3.2.13 on 2022-05-16 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0004_auto_20220515_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='spent_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 10, 15, 23, 616204), verbose_name='Time spent'),
        ),
    ]
