# Generated by Django 3.2.13 on 2022-05-16 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0005_alter_spending_spent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='currency',
            field=models.CharField(default='HUF', max_length=3),
        ),
        migrations.AlterField(
            model_name='spending',
            name='spent_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 10, 22, 25, 477616), verbose_name='Time spent'),
        ),
    ]
