# Generated by Django 3.2.13 on 2022-05-16 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0007_auto_20220516_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='spent_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 18, 19, 752662), verbose_name='Time spent'),
        ),
    ]
