# Generated by Django 3.2.13 on 2022-05-16 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0008_alter_spending_spent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='spent_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 18, 44, 703453), verbose_name='Time spent'),
        ),
    ]
